import { Event, PortfolioPosition, CausalEdge, ConfirmationAlert } from "../types";

export const events: Event[] = [
  {
    id: "evt-001",
    title: "DOE announces expanded EV battery domestic-content subsidy",
    titleKo: "미 에너지부, 전기차 배터리 국내 생산 보조금 확대 발표",
    eventType: "policy_announcement",
    actor: "U.S. Department of Energy",
    actorKo: "미국 에너지부",
    action: "announced",
    object: "subsidy eligibility conditions",
    magnitude: { value: 7.5, unit: "USD bn" },
    effectiveDate: "2026-07-15",
    publishedAt: "2026-07-02T09:30:00Z",
    sourceType: "official",
    sourceReliability: 0.98,
    evidenceGrade: "E4",
    urgency: "High",
    status: "Active",
    actionRequired: "Research Required",
    lat: 38.9,
    lng: -77.0,
    count: 102,
    sector: "CleanTech / Battery",
    sectorKo: "클린테크 / 배터리",
    relatedTickers: ["TSLA", "QS", "LAC", "MP", "ALB"],
    scenarios: [
      { name: "Bull", probability: 0.42, prevProbability: 0.30, conditions: ["국내 생산 비율 기준 유지", "캐소드 공급 계속 타이트"], priceRange: "+15% ~ +28%" },
      { name: "Base", probability: 0.38, prevProbability: 0.40, conditions: ["부품사 일부만 수혜"], priceRange: "+4% ~ +12%" },
      { name: "Bear", probability: 0.20, prevProbability: 0.30, conditions: ["규정 지연", "해외 합작사도 자격 부여"], priceRange: "-6% ~ -14%" },
    ],
    mechanism: "Domestic-content rules reroute demand toward North American battery-material suppliers, tightening qualified supply.",
    mechanismKo: "국내 생산 조건이 북미 배터리 소재 수요를 몰아주면서 '자격 있는 공급'이 줄어듦.",
    counterevidence: ["ALB already expanded Chile contract", "Tesla vertical integration may absorb margin"],
    counterevidenceKo: ["ALB가 칠레 계약을 확대한 상태", "테슬라가 수직계열화로 마진을 흡수할 수 있음"],
    nextEvents: ["Treasury guidance Jul 10", "ALB Q2 call Jul 17"],
    nextEventsKo: ["재무부 가이던스 7/10", "ALB 2분기 실적발표 7/17"],
  },
  {
    id: "evt-002",
    title: "SEC filing: major semiconductor foundry cuts capex guidance 12%",
    titleKo: "TSMC, 투자 지침 12% 하향 수정 공시",
    eventType: "filing",
    actor: "TSMC",
    actorKo: "TSMC",
    action: "cut",
    object: "capex guidance",
    magnitude: { value: -12, unit: "percent" },
    effectiveDate: "2026-07-02",
    publishedAt: "2026-07-02T08:15:00Z",
    sourceType: "filing",
    sourceReliability: 0.97,
    evidenceGrade: "E4",
    urgency: "Critical",
    status: "At Risk",
    actionRequired: "Reduce",
    lat: 25.0,
    lng: 121.5,
    count: 65,
    sector: "Semiconductors",
    sectorKo: "반도체",
    relatedTickers: ["NVDA", "AMD", "ASML", "AMAT", "LRCX"],
    scenarios: [
      { name: "Bull", probability: 0.18, prevProbability: 0.25, conditions: ["투자 삭감이 일시적", "백로그는 유지"], priceRange: "+5% ~ +10%" },
      { name: "Base", probability: 0.40, prevProbability: 0.45, conditions: ["장비 수요가 2027년으로 밀림"], priceRange: "-2% ~ +3%" },
      { name: "Bear", probability: 0.42, prevProbability: 0.30, conditions: ["AI 투자 정점 우려"], priceRange: "-12% ~ -22%" },
    ],
    mechanism: "Lower foundry capex directly reduces near-term equipment orders and may signal AI demand deceleration.",
    mechanismKo: "파운드리 투자 감소는 단기 장비 주문을 줄이고, AI 수요 둔화 신호로 읽힘.",
    counterevidence: ["Microsoft reaffirmed datacenter build plans", "HBM supply still sold out"],
    counterevidenceKo: ["MS, 데이터센터 건설 계획 재확인", "HBM 공급 여전히 매진"],
    nextEvents: ["NVDA analyst day Jul 08", "Taiwan export data Jul 12"],
    nextEventsKo: ["엔비디아 애널리스트 데이 7/8", "대만 수출 데이터 7/12"],
  },
  {
    id: "evt-003",
    title: "EIA reports surprise crude inventory draw as refining runs pick up",
    titleKo: "EIA, 정제 가동률 상승에 예상 밖 원유 재고 감소 발표",
    eventType: "macro",
    actor: "EIA",
    actorKo: "미 EIA",
    action: "reported",
    object: "inventory draw",
    magnitude: { value: -4.2, unit: "mmbbl" },
    effectiveDate: "2026-07-01",
    publishedAt: "2026-07-02T14:30:00Z",
    sourceType: "official",
    sourceReliability: 0.96,
    evidenceGrade: "E3",
    urgency: "Medium",
    status: "Watching",
    actionRequired: "Watch",
    lat: 29.7,
    lng: -95.3,
    count: 58,
    sector: "Energy",
    sectorKo: "에너지",
    relatedTickers: ["XLE", "CVX", "XOM", "OXY", "USO"],
    scenarios: [
      { name: "Bull", probability: 0.35, prevProbability: 0.32, conditions: ["재고 감소 지속", "OPEC+ 감산 유지"], priceRange: "+6% ~ +12%" },
      { name: "Base", probability: 0.45, prevProbability: 0.48, conditions: ["정유소 재가동 일회성 효과"], priceRange: "+1% ~ +4%" },
      { name: "Bear", probability: 0.20, prevProbability: 0.20, conditions: ["수요 지표 악화", "OPEC+ 증산"], priceRange: "-5% ~ -10%" },
    ],
    mechanism: "Inventory draw tightens prompt physical markets and can shift futures curve backwardation.",
    mechanismKo: "재고 감소는 현물 시장을 타이트하게 만들고 선물 곡선을 백워데이션으로 전환할 수 있음.",
    counterevidence: ["Gasoline demand 4-week avg still down YoY", "Strategic reserve release rumor"],
    counterevidenceKo: ["휘발유 수요 4주 평균 전년 대비 감소", "전략비축유 방출 루머"],
    nextEvents: ["OPEC+ JMMC Jul 05", "Cushing storage report Jul 09"],
    nextEventsKo: ["OPEC+ JMMC 7/5", "쿠싱 저장고 보고서 7/9"],
  },
  {
    id: "evt-004",
    title: "FDA accepts Biotech X's accelerated approval filing for oncology asset",
    titleKo: "FDA, 바이오텍 X 종양 자산 가속 승인 신청 접수",
    eventType: "regulatory",
    actor: "FDA",
    actorKo: "FDA",
    action: "accepted",
    object: "accelerated approval filing",
    magnitude: { value: 1, unit: "event" },
    effectiveDate: "2026-07-02",
    publishedAt: "2026-07-02T11:00:00Z",
    sourceType: "official",
    sourceReliability: 0.95,
    evidenceGrade: "E3",
    urgency: "High",
    status: "Strengthening",
    actionRequired: "Paper Trade",
    lat: 39.0,
    lng: -77.1,
    count: 35,
    sector: "Biotech",
    sectorKo: "바이오텍",
    relatedTickers: ["XBI", "IBB", "VRTX", "REGN", "BMY"],
    scenarios: [
      { name: "Bull", probability: 0.30, prevProbability: 0.22, conditions: ["PDUFA 일정 단축", "확증 시험 등록 완료"], priceRange: "+25% ~ +45%" },
      { name: "Base", probability: 0.50, prevProbability: 0.55, conditions: ["표준 PDUFA 일정"], priceRange: "+5% ~ +15%" },
      { name: "Bear", probability: 0.20, prevProbability: 0.23, conditions: ["OS 추이에 대한 Adcom 우려"], priceRange: "-15% ~ -30%" },
    ],
    mechanism: "Regulatory acceptance starts review clock and often re-rates probability-weighted peak sales.",
    mechanismKo: "규제 접수로 심사 시계가 시작되고, 확률 가중 정점 매출이 재평가됨.",
    counterevidence: ["Competitor readout showed similar PFS but no OS benefit"],
    counterevidenceKo: ["경쟁사 데이터: PFS 유사 but OS 이점 없음"],
    nextEvents: ["Adcom date expected Aug", "Competitor ASCO data Jul 22"],
    nextEventsKo: ["Adcom 일정 8월 예정", "경쟁사 ASCO 데이터 7/22"],
  },
  {
    id: "evt-005",
    title: "Polymarket: Fed cut probability for July jumps to 72% after Powell remarks",
    titleKo: "Polymarket: 파월 발언 후 7월 금리 인하 확률 72% 급등",
    eventType: "prediction_market",
    actor: "Polymarket",
    actorKo: "Polymarket",
    action: "priced",
    object: "Fed cut probability",
    magnitude: { value: 72, unit: "percent" },
    effectiveDate: "2026-07-02",
    publishedAt: "2026-07-02T16:45:00Z",
    sourceType: "wire",
    sourceReliability: 0.85,
    evidenceGrade: "E2",
    urgency: "Medium",
    status: "Active",
    actionRequired: "Research Required",
    lat: 40.7,
    lng: -74.0,
    count: 21,
    sector: "Macro / Rates",
    sectorKo: "매크로 / 금리",
    relatedTickers: ["TLT", "GLD", "DXY", "QQQ", "SIVB"],
    scenarios: [
      { name: "Bull", probability: 0.40, prevProbability: 0.28, conditions: ["7월 인하 확정", "달러 약세"], priceRange: "+8% ~ +14%" },
      { name: "Base", probability: 0.35, prevProbability: 0.42, conditions: ["인하가 9월로 밀림"], priceRange: "+2% ~ +6%" },
      { name: "Bear", probability: 0.25, prevProbability: 0.30, conditions: ["강한 고용 보고서로 가격 되돌림"], priceRange: "-5% ~ -11%" },
    ],
    mechanism: "Rate-cut expectations are a latent factor; Polymarket is one sensor among yields, futures and FX.",
    mechanismKo: "금리 인하 기대는 잠재 요인이다. Polymarket은 수익률/선물/FX 중 하나의 센서일 뿐.",
    counterevidence: ["2Y yield barely moved", "Fed speakers this week hawkish"],
    counterevidenceKo: ["2년물 수익률 거의 움직임 없음", "이번 주 연준 발언 매파적"],
    nextEvents: ["Nonfarm payrolls Jul 03", "CPI Jul 15"],
    nextEventsKo: ["비농업 고용 7/3", "CPI 7/15"],
  },
  {
    id: "evt-006",
    title: "Copper mine union in Chile calls indefinite strike starting next week",
    titleKo: "칠레 구리 광산 노조, 다음 주 무기한 파업 예고",
    eventType: "supply_chain",
    actor: "Union",
    actorKo: "노조",
    action: "called",
    object: "strike",
    magnitude: { value: 1, unit: "event" },
    effectiveDate: "2026-07-09",
    publishedAt: "2026-07-02T07:20:00Z",
    sourceType: "wire",
    sourceReliability: 0.80,
    evidenceGrade: "E2",
    urgency: "High",
    status: "Watching",
    actionRequired: "Watch",
    lat: -22.5,
    lng: -68.9,
    count: 8,
    sector: "Materials",
    sectorKo: "소재",
    relatedTickers: ["FCX", "SCCO", "COPX", "GC=F"],
    scenarios: [
      { name: "Bull", probability: 0.35, prevProbability: 0.25, conditions: ["파업 2주 이상 지속", "LME 재고 부족"], priceRange: "+10% ~ +18%" },
      { name: "Base", probability: 0.40, prevProbability: 0.45, conditions: ["단기 파업, 부분 생산"], priceRange: "+2% ~ +6%" },
      { name: "Bear", probability: 0.25, prevProbability: 0.30, conditions: ["정부 중재로 조기 종료"], priceRange: "-3% ~ -8%" },
    ],
    mechanism: "Supply disruption in a concentrated copper region tightens concentrate and cathode availability.",
    mechanismKo: "구리 공급이 집중된 지역의 생산 차질로 정광/캐소드 공급이 줄어듦.",
    counterevidence: ["China copper imports slowed", "smelters have buffer stocks"],
    counterevidenceKo: ["중국 구리 수입 둔화", "제련소 버퍼 재고 보유"],
    nextEvents: ["Government mediation meeting Jul 06", "LME stocks update Jul 08"],
    nextEventsKo: ["정부 중재 회의 7/6", "LME 재고 업데이트 7/8"],
  },
  {
    id: "evt-007",
    title: "Tech giant files 8-K disclosing material cyber incident in cloud unit",
    titleKo: "큰 기업, 클라우드 부문 8-K 중대 사이버 사고 공시",
    eventType: "filing",
    actor: "Major Cloud Provider",
    actorKo: "대형 클라우드 기업",
    action: "filed",
    object: "8-K cyber incident",
    magnitude: { value: 1, unit: "event" },
    effectiveDate: "2026-07-02",
    publishedAt: "2026-07-02T06:50:00Z",
    sourceType: "filing",
    sourceReliability: 0.95,
    evidenceGrade: "E4",
    urgency: "Critical",
    status: "At Risk",
    actionRequired: "Reduce",
    lat: 47.6,
    lng: -122.3,
    count: 2,
    sector: "Cybersecurity / Cloud",
    sectorKo: "사이버보안 / 클라우드",
    relatedTickers: ["CRWD", "PANW", "FTNT", "CYBR", "OKTA"],
    scenarios: [
      { name: "Bull", probability: 0.15, prevProbability: 0.20, conditions: ["사고 통제, 데이터 유실 없음"], priceRange: "+2% ~ +5%" },
      { name: "Base", probability: 0.45, prevProbability: 0.50, conditions: ["단기 이탈, 복구 비용"], priceRange: "-5% ~ -12%" },
      { name: "Bear", probability: 0.40, prevProbability: 0.30, conditions: ["규제 조사, 기업 이탈"], priceRange: "-18% ~ -30%" },
    ],
    mechanism: "Material cyber incidents can trigger regulatory scrutiny, customer churn and insurance/remediation costs.",
    mechanismKo: "중대 사이버 사고는 규제 감시, 고객 이탈, 보험/복구 비용을 유발할 수 있음.",
    counterevidence: ["Incident appears limited to non-production environment"],
    counterevidenceKo: ["비생산 환경으로 한정된 것으로 보임"],
    nextEvents: ["Forensic report due Jul 09", "Senate hearing Jul 11"],
    nextEventsKo: ["포렌식 보고서 7/9", "상원 청문회 7/11"],
  },
];

export const portfolio: PortfolioPosition[] = [
  { ticker: "LAC", name: "Lithium Americas", shares: 1200, avgCost: 4.85, currentPrice: 5.62, plPercent: 15.9, plUsd: 924, exposureEvents: ["evt-001"], scenarioBias: "Bull" },
  { ticker: "NVDA", name: "NVIDIA", shares: 50, avgCost: 875.0, currentPrice: 812.5, plPercent: -7.1, plUsd: -3125, exposureEvents: ["evt-002", "evt-005"], scenarioBias: "Bear" },
  { ticker: "XLE", name: "Energy Select SPDR", shares: 300, avgCost: 88.4, currentPrice: 91.2, plPercent: 3.2, plUsd: 840, exposureEvents: ["evt-003"], scenarioBias: "Base" },
  { ticker: "XBI", name: "Biotech ETF", shares: 200, avgCost: 78.0, currentPrice: 84.5, plPercent: 8.3, plUsd: 1300, exposureEvents: ["evt-004"], scenarioBias: "Bull" },
  { ticker: "TLT", name: "20+ Year Treasury", shares: 150, avgCost: 92.0, currentPrice: 94.8, plPercent: 3.0, plUsd: 420, exposureEvents: ["evt-005"], scenarioBias: "Bull" },
];

export const causalEdges: CausalEdge[] = [
  { source: "evt-005", target: "evt-002", strength: 7, type: "market", labelKo: "금리 인하 기대가 AI 투자 심리를 떠받치지만, 동시에 수요 정점 의심도 키움" },
  { source: "evt-002", target: "evt-005", strength: 4, type: "market", labelKo: "반도체 투자 둔화는 성장 둔화 신호로 금리 인하 확률에 영향" },
  { source: "evt-001", target: "evt-006", strength: 3, type: "supply_chain", labelKo: "배터리 수요 증가가 구리/니켈 수요로 이어질 수 있음" },
  { source: "evt-003", target: "evt-005", strength: 6, type: "latent", labelKo: "유가 상승은 인플레이션 기대를 높여 금리 인하 확률을 낮출 수 있음" },
  { source: "evt-007", target: "evt-002", strength: 2, type: "causal", labelKo: "클우드 사고는 AI 인프라 신뢰도에 간접 영향" },
  { source: "evt-004", target: "evt-007", strength: 1, type: "causal", labelKo: "직접적 연결은 약함" },
];

export const confirmationAlerts: ConfirmationAlert[] = [
  { eventId: "evt-001", scenario: "Bull", whatToWatch: "재무부가 국내 생산 비율을 어떻게 해석하는지", deadline: "7월 10일", impactIfConfirmed: "배터리 소재주 추가 상승 가능" },
  { eventId: "evt-002", scenario: "Bear", whatToWatch: "NVDA 애널리스트 데이에서 AI 수요 가이던스", deadline: "7월 8일", impactIfConfirmed: "반도체 장비주 추가 하락" },
  { eventId: "evt-005", scenario: "Bull", whatToWatch: "금요일 고용 보고서가 연준 기대를 뒤집지 않는지", deadline: "7월 3일", impactIfConfirmed: "장기국채/금리 민감주 랠리" },
];

export const filters = {
  eventTypes: ["All", "policy_announcement", "filing", "earnings", "macro", "supply_chain", "regulatory", "prediction_market"],
  evidenceGrades: ["All", "E0", "E1", "E2", "E3", "E4"],
  urgencies: ["All", "Low", "Medium", "High", "Critical"],
  statuses: ["All", "Active", "Strengthening", "At Risk", "Invalidated", "Resolved", "Watching"],
  sectors: ["All", "CleanTech / Battery", "Semiconductors", "Energy", "Biotech", "Macro / Rates", "Materials", "Cybersecurity / Cloud"],
};
