"""initial schema

Revision ID: 7e959c2ba872
Revises: 
Create Date: 2026-07-02 02:15:20.420469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e959c2ba872'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('identifiers', sa.JSON(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_key', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('object', sa.String(), nullable=True),
    sa.Column('magnitude_value', sa.Float(), nullable=True),
    sa.Column('magnitude_unit', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_reliability', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('evidence_grade', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_ko', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('sector_ko', sa.String(), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('mechanism_ko', sa.Text(), nullable=True),
    sa.Column('related_tickers', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('counterevidence', sa.JSON(), nullable=True),
    sa.Column('counterevidence_ko', sa.JSON(), nullable=True),
    sa.Column('next_events', sa.JSON(), nullable=True),
    sa.Column('next_events_ko', sa.JSON(), nullable=True),
    sa.Column('source_document_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_table('latent_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sensors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('market_instruments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('asset_class', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('input_hash', sa.String(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('avg_cost', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('pl_percent', sa.Float(), nullable=True),
    sa.Column('pl_usd', sa.Float(), nullable=True),
    sa.Column('exposure_events', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('scenario_bias', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_tier', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_table('market_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['market_instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('mechanism_ko', sa.Text(), nullable=True),
    sa.Column('lag_window_min_hours', sa.Integer(), nullable=True),
    sa.Column('lag_window_max_hours', sa.Integer(), nullable=True),
    sa.Column('evidence_grade', sa.String(), nullable=True),
    sa.Column('historical_stability', sa.Float(), nullable=True),
    sa.Column('current_regime_fit', sa.Float(), nullable=True),
    sa.Column('redundancy_group', sa.String(), nullable=True),
    sa.Column('source_refs', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('raw_payload_ref', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'content_hash', name='uq_source_doc_hash')
    )
    op.create_table('theses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('core_event_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('time_window', sa.String(), nullable=True),
    sa.Column('portfolio_overlap', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['core_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thesis_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('reason_summary', sa.Text(), nullable=True),
    sa.Column('counterevidence_summary', sa.Text(), nullable=True),
    sa.Column('input_data_cutoff_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_document_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('evidence_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('ontology_version', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('human_approval_state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('claim_text', sa.Text(), nullable=True),
    sa.Column('claim_text_ko', sa.Text(), nullable=True),
    sa.Column('evidence_grade', sa.String(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thesis_id', sa.UUID(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('costs', sa.Float(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thesis_id', sa.UUID(), nullable=False),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thesis_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('prev_probability', sa.Float(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('price_range', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thesis_scenarios')
    op.drop_table('thesis_conditions')
    op.drop_table('paper_trades')
    op.drop_table('evidence_items')
    op.drop_table('decision_logs')
    op.drop_table('theses')
    op.drop_table('source_documents')
    op.drop_table('relations')
    op.drop_table('market_prices')
    op.drop_table('sources')
    op.drop_table('prompt_versions')
    op.drop_table('portfolio_positions')
    op.drop_table('model_runs')
    op.drop_table('market_instruments')
    op.drop_table('latent_factors')
    op.drop_table('events')
    op.drop_table('entities')
    # ### end Alembic commands ###
