"""add_backtest_runs

Revision ID: ab2bfd272465
Revises: 78214c6684ef
Create Date: 2026-07-02 09:39:21.953951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2bfd272465'
down_revision: Union[str, None] = '78214c6684ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('snapshot_summary', sa.JSON(), nullable=True),
    sa.Column('predictions_generated', sa.Integer(), nullable=True),
    sa.Column('predictions_resolved', sa.Integer(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('log_loss', sa.Float(), nullable=True),
    sa.Column('calibration_curve', sa.JSON(), nullable=True),
    sa.Column('failure_analysis', sa.JSON(), nullable=True),
    sa.Column('improvement_decision', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('prediction_records', sa.Column('backtest_run_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'prediction_records', 'backtest_runs', ['backtest_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prediction_records', type_='foreignkey')
    op.drop_column('prediction_records', 'backtest_run_id')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
