"""add_event_relations

Revision ID: e9e011e32655
Revises: f9774caafbcf
Create Date: 2026-07-02 03:05:40.249848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9e011e32655'
down_revision: Union[str, None] = 'f9774caafbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('target_event_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('mechanism_ko', sa.Text(), nullable=True),
    sa.Column('source_refs', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['target_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event_id', 'target_event_id', 'edge_type', name='uq_event_relation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_relations')
    # ### end Alembic commands ###
