"""add actor_ko

Revision ID: f9774caafbcf
Revises: 7e959c2ba872
Create Date: 2026-07-02 02:23:13.772182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9774caafbcf'
down_revision: Union[str, None] = '7e959c2ba872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('actor_ko', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'actor_ko')
    # ### end Alembic commands ###
